Learn:
  feature_number: 12 #48
  save_mother_dir: '/Local-Scratch'
  batch_size: 32
  keep_prob: 1
  learning_rate: 0.00001
  number_of_total_game: 1202
  max_seq_length: 10
  feature_type: 'v1'
  iterate_num: 1
  model_type: 'v1'
  predict_target : 'PlayerId'

Arch:
  LSTM:
    h_size: 512
    lstm_layer_num: 1
  Encode:
    latent_size: 1024
    label_size: 1003
  Dense:
    dense_layer_num : 2
    output_layer_size: 33
    apply_softmax: True
    hidden_node_size: 256

  Feature:
    feature_layer_num : 2
    hidden_node_size : 256