Learn:
  save_mother_dir: '/Local-Scratch'
  batch_size: 32
  keep_prob: 1
  learning_rate: 0.00001
  gaussian_size: 1
  number_of_total_game: 1202
  max_seq_length: 10
  feature_type: 'v1'
  iterate_num: 10
  model_type: 'v1'
  player_Id_style : 'PlayerId'
  predict_target : 'Qs'
  sport : 'Ice-Hockey'
  apply_softmax : True
  apply_box_score: False
  apply_pid: True

Arch:
  LSTM:
    h_size: 512
    lstm_layer_num: 1
    feature_number: 1042 #27+12+1003
  Dense:
    dense_layer_num : 2
    hidden_size: 256
    output_layer_size : 3
