Learn:
  save_mother_dir: '/Local-Scratch'
  batch_size: 32
  keep_prob: 1
  learning_rate: 0.00001
  number_of_total_game: 1202
  max_seq_length: 10
  feature_type: 'v1'
  iterate_num: 1
  model_type: 'v1'
  player_Id_style : 'PlayerId'
  predict_target : 'reward'
  sport : 'Ice-Hockey'

Arch:
  LSTM:
    h_size: 512
    lstm_layer_num: 1
    feature_number: 42 #27+12+3
  Embed:
    embed_size: 1024*3
    latent_size: 1024
    embed_layer_num: 1
  Dense:
    dense_layer_num : 2
    output_layer_size: 3
    apply_softmax: False
    hidden_node_size: 256
