name_matching = {'Matthew|Murray': 'Matt|Murray',
                 'MacKenzie|Blackwood': 'Mackenzie|Blackwood',
                 'Jakob|Forsbacka Karlsson': 'Jakob|Karlsson',
                 'Max|Veronneau': 'Max|V\xc3\xa9ronneau',
                 'James|van Riemsdyk': 'James|Riemsdyk',
                 'Louis|Belpedio': 'Louie|Belpedio',
                 'TJ|Brodie': 'T.J.|Brodie',
                 'Michael|Del Zotto': 'Michael|Zotto',
                 'J-F|Berube': 'Jean-Francois|Berube',
                 "Daniel|O'Regan": "Danny|O'Regan",
                 "Vincent|Hinostroza": "Vinnie|Hinostroza",
                 "William|Borgen": "Will|Borgen",
                 "Cameron|Johnson": "Cam|Johnson",
                 "Joshua|Morrissey": "Josh|Morrissey",
                 "Phillip|Di Giuseppe": "Phillip|Giuseppe",
                 "Quintin|Hughes": "Quinn|Hughes",
                 "Timothy|Gettinger": "Tim|Gettinger",
                 "Theodor|Blueger": "Teddy|Blueger",
                 "Steven|Santini": "Steve|Santini",
                 "Benjamin|Gleason": "Ben|Gleason",
                 "Alex|Debrincat": "Alex|DeBrincat",
                 "Joseph|Gambardella": "Joe|Gambardella",
                 "Nick|Paul": "Nicholas|Paul",
                 "Alexander|Petrovic": "Alex|Petrovic",
                 "Joshua|Ho-Sang": "Josh|Ho-Sang",
                 "Michael|Dal Colle": "Michael|Colle",
                 "Matt|Dumba": "Mathew|Dumba",
                 "Joshua|Mahura": "Josh|Mahura",
                 "Calvin|De Haan": "Calvin|Haan",
                 "Trevor|van Riemsdyk": "Trevor|Riemsdyk",
                 "Mike|Matheson": "Michael|Matheson",
                 "Phil|Varone": "Philip|Varone",
                 "Tony|DeAngelo": "Anthony|DeAngelo",
                 "MacKenzie|MacEachern": "Mackenzie|MacEachern",
                 "Joel|Eriksson Ek": "Joel|Ek",
                 "Maxime|Lajoie": "Max|Lajoie",
                 "Matt|Puempel": "Matthew|Puempel"
                 }

team_matching = {'LAK': 'LA', 'SJS': 'SJ', 'NJD': 'NJ', 'TBL': 'TB'}
